---
title: "Cluster by Cell Type"
author: "Nathan"
date: "February 16, 2018"
output: html_document
---
```{r, include=FALSE}
library(sp.scRNAseq)
library(tidyverse)
extrafont::loadfonts(device="win")
source("RNAseq_functs.R")


```

```{r}

load("C:/Users/Nathanael/Desktop/Smartseq dataanalysis/counts_raw_and_log_180112.rda")
load("C:/Users/Nathanael/Desktop/Smartseq dataanalysis/counts_ercc.rda")


#remove .htseq suffix
colnames(counts) <- str_replace(colnames(counts), "(.*)\\.htseq$", "\\1")

#move ercc
ercc <- grepl("^ERCC\\-[0-9]*$", rownames(counts.ercc))

c <- grepl(".C1.", colnames(counts)) | grepl("NJA00109", colnames(counts)) | grepl("NJA00204", colnames(counts)) | grepl("NJA00205", colnames(counts)) | grepl("NJA00206", colnames(counts))

C.counts <- counts[, c]

C.countsERCC <- C.counts[ercc, ]

C.counts <- C.counts[!ercc, ]

countsERCC <- counts.ercc


#remove cells with poor coverage
mincount <- 1e5
countsERCC <- countsERCC[, colSums(counts, na.rm = TRUE) > mincount]
counts <- counts[, colSums(counts, na.rm = TRUE) > mincount]
C.countsERCC <- C.countsERCC[, colSums(C.counts, na.rm = TRUE) > mincount]
C.counts <- C.counts[, colSums(C.counts, na.rm = TRUE) > mincount]

counts[is.na(counts)] <- 0
countsERCC[is.na(countsERCC)] <- 0
C.counts[is.na(C.counts)] <- 0
C.countsERCC[is.na(C.countsERCC)] <- 0

#remove "bad" genes
counts <- counts[rowSums(counts) > 0, ]
C.counts <- C.counts[rowSums(C.counts) > 0, ]

nonGenes <- c(
  "__no_feature", "__ambiguous", "__too_low_aQual",
  "__not_aligned", "__alignment_not_unique"
)

counts <- counts[!rownames(counts) %in% nonGenes, ]
C.counts <- C.counts[!rownames(C.counts) %in% nonGenes, ]


s <- grepl("SRR", colnames(counts)) | grepl("Singlet", colnames(counts)) | grepl("NJA00102", colnames(counts)) | grepl("NJA00103", colnames(counts)) | grepl("NJA00104", colnames(counts)) | grepl("NJA00109", colnames(counts)) | grepl("NJA00204", colnames(counts)) | grepl("NJA00205", colnames(counts)) | grepl("NJA00206", colnames(counts))


cObjSng <- spCounts(counts[, s], countsERCC[, s])
cObjMul <- spCounts(counts[, !s], countsERCC[, !s])

plotCounts(cObjSng, cObjMul, type = "ercc") # <---- Ask Jason for help
plotCounts(cObjSng, cObjMul, type = "markers", markers = c("Alpi", "Reg4"))

uObj <- spUnsupervised(cObjSng)
plotUnsupervised(uObj)
plotUnsupervised(uObj, cObjSng, type = "markers", markers = c("Lgr5", "Olfm4"))
plotUnsupervised(uObj, cObjSng, type = "markers", markers = c("Alpi", "Muc2"))
plotUnsupervised(uObj, cObjSng, type = "markers", markers = c("Lyz1", "Reg4"))
plotUnsupervised(uObj, cObjSng, type = "markers", markers = c("Ptprc", "Dclk1"))
plotUnsupervised(uObj, cObjSng, type = "markers", markers = c("Mboat1", "Chga"))

classification <- getData(uObj, "classification")
names(classification) <- getData(uObj, "tsne") %>%
  rownames()

SI.Stem <- names(classification)[classification %in% c("A1", "J1", "K1", "N1", "T1")]
SI.TA.Cells <- names(classification)[classification %in% c("R1", "C1", "B1")]
SI.Enterocyte.Progenitor <- names(classification)[classification %in% c("E1", "Q1")]
SI.Early.Enterocyte <- names(classification)[classification == "G1"]
SI.Late.Enterocyte <- names(classification)[classification == "M1"]
SI.Paneth <- names(classification)[classification %in% c("P1", "O1")]
SI.Goblet <- names(classification)[classification %in% c("F1", "L1")]
Blood.Cells <- names(classification)[classification == "D1"]
SI.Tuft.Cells <- names(classification)[classification == "H1"]
SI.Enteroendocrine <- names(classification)[classification == "S1"]
Colon <- names(classification)[classification == "I1"]



#tSNE for colon cells

cs <- colnames(counts) %in% Colon

colcObjSng <- spCounts(counts[, cs], countsERCC[, cs])

C.uObj <- spUnsupervised(colcObjSng)
plotUnsupervised(C.uObj)
plotUnsupervised(C.uObj, colcObjSng, type = "markers", markers = c("Lgr5", "Muc2"))
plotUnsupervised(C.uObj, colcObjSng, type = "markers", markers = c("Car1", "Ptprc"))


#Select and rename clusters according to cell type


C.classification <- getData(C.uObj, "classification")
names(C.classification) <- getData(C.uObj, "tsne") %>%
  rownames()

C.Stem <- names(C.classification)[C.classification == "B1"]
C.Goblet <- names(C.classification)[C.classification == "C1"]
C.Colonocytes <- names(C.classification)[C.classification == "A1"]


celltypes <- data.frame(
  Samples = c(SI.Early.Enterocyte, SI.Enterocyte.Progenitor, SI.Enteroendocrine, SI.Goblet, SI.Late.Enterocyte, SI.Paneth, SI.Stem, SI.TA.Cells, C.Colonocytes, C.Goblet, C.Stem, SI.Tuft.Cells, Blood.Cells),
  class = c(rep("SI.Early.Enterocyte", length(SI.Early.Enterocyte)), rep("SI.Enterocyte.Progenitor", length(SI.Enterocyte.Progenitor)), rep("SI.Enteroendocrine", length(SI.Enteroendocrine)), rep("SI.Goblet", length(SI.Goblet)), rep("SI.Late.Enterocyte", length(SI.Late.Enterocyte)), rep("SI.Paneth", length(SI.Paneth)), rep("SI.Stem", length(SI.Stem)), rep("SI.TA.Cells", length(SI.TA.Cells)), rep("C.Colonocytes", length(C.Colonocytes)), rep("C.Goblet", length(C.Goblet)), rep("C.Stem", length(C.Stem)), rep("SI.Tuft.Cells", length(SI.Tuft.Cells)), rep("Blood.Cells", length(Blood.Cells))) 
)


newclass <- celltypes[match(rownames(getData(uObj, "tsne")), celltypes$Samples),]

newclass2 <- as.vector(newclass$class)

uObj@classification <- newclass2


plotUnsupervised(uObj)

#sObj <- spSwarm(cObjMul, uObj, distFun = "distToSliceNorm")
#plotSwarm(sObj, uObj, cObjSng, cObjMul, type = "tsne")
#plotSwarm(sObj, uObj, cObjSng, cObjMul, type = "heat")
#tsne <- getData(uObj, "tsne")
#plot.nice(tsne, gene.vals=counts.log, genes=c("Lyz1", "Alpi", "Lgr5", "Reg4", "Dll4"), cex=2)


```

```{r}
sessionInfo()
```